version: "3"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - JWT_SECRET=${JWT_SECRET}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3333:3333"
    volumes:
      - .:/server
    depends_on:
      - db
    command: sh -c 'npx prisma generate --schema ./prisma/schema.prisma && npx prisma migrate deploy && npx prisma migrate deploy && yarn build && yarn start:dev'

  db:
    container_name: postgres
    image: bitnami/postgresql:13.16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=locahost
      - POSTGRES_DB=supermega

volumes:
  postgres_data:
    driver: local
